#!/bin/bash
  
if [ "$#" -ne 1 ]; then
    echo "try: $0 urls.txt"
    exit 1
fi

input_file="$1"
output_file="directories.txt"

> "$output_file"

while IFS= read -r url || [[ -n "$url" ]]; do
    echo "---------------------------------" | tee -a "$output_file"
    echo "Processing $url" | tee -a "$output_file"
    echo "---------------------------------" | tee -a "$output_file"

    # Executa Katana
    echo "[+] Executing Katana..." | tee -a "$output_file"
    katana -u "$url" -silent | tee -a "$output_file"

    # Executa gau
    echo "[+] Executing gau..." | tee -a "$output_file"
    gau "$url" | tee -a "$output_file"

    # Executa waybackurls
    echo "[+] Executing waybackurls..." | tee -a "$output_file"
    echo "$url" | waybackurls | tee -a "$output_file"

    echo "" | tee -a "$output_file"

done < "$input_file"

echo "Done, saving output in $output_file"
